import 'package:get/get.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'zh_CN': {
          'quit_bad_habit': '远离不良生活习惯',
          'health_life': '开启健康生活',
          'challenge_target': '挑战目标',
          'start_at': "开始于：",
          'days': "天",
          'hours': '时',
          'mins': '分',
          'secs': '秒',
          'all': "全部",
          'congraulations': '恭喜你，你已完成目标！',
          'regret': '很遗憾，你已经放弃目标',
          'journey': '历程',
          'challenge_begin': '挑战开始',
          'challenge_completed': '挑战完成',
          'challenge_giveup': '放弃挑战',
          'giveup_challenge': '放弃挑战',
          'cancel': '取消',
          'save': '保存',
          'select_day': '坚持天数：',
          'custom_days': '自定义天数：',
          'select_color': '选择颜色：',
          'notify_sound': '提醒声音：',
          'notify_time': '定时通知：',
          'select_sound': '选择通知声音',
          'confirm': '确定',
          'progressing': '进行中',
          'completed': '完成',
          'giveup': '放弃',
          'try_exercise': '尝试着去做一些运动吧！',
          'target is ongoing': '该目标正在挑战中...',
          'set days': '请设置目标天数',
          'save success': '保存成功',
          'save failed': '保存失败',
          'go to setting': '前往设置',
          'album permission': '保存图片到相册需要打开系统相册权限，可前往“设置”打开',
          'go to': '前往',
          'notification setting': '推送设置',
          'notification permission': '关闭系统推送，你将不能及时收到推送，可前往“设置”打开',
          'sound_lg': 'LG经典',
          'sound_pikachu': '皮卡丘',
          'sound_ringtones': '叮咚',
          'sound_samsung': '三星经典',
          'sound_spring': '上升',
          'refresh_idle_text': '下拉刷新',
          'refresh_releasing_text': '松开手指，刷新',
          'refresh_complete_text': '刷新完成',
          'push_text_1': '恭喜你，好的开始！',
          'push_text_2': '你已经坚持',
          'push_text_3': '天，继续加油！',
          'push_text_4': '恭喜你，你已完成目标！',
          'help': '帮助',
          'praise': '给好评',
          'feedback': '合作反馈',
          'policy': '隐私政策',
          'policy_text':
              '本应用尊重并保护所有使用服务用户的个人隐私权。为了给您提供更准确、更有个性化的服务。本应用将以高度的勤勉、审慎义务对待这些信息。除本隐私权政策另有规定外，在未征得您事先许可的情况下，本应用不会将这些信息对外披露或向第三方提供。本应用会不时更新本隐私权政策。 您在同意本应用服务使用协议之时，即视为您已经同意本隐私权政策全部内容。本隐私权政策属于本应用服务使用协议不可分割的一部分。\n\n(A)本应用不会向任何无关第三方提供、出售、出租、分享或交易您的个人信息，除非事先得到您的许可，或该第三方和本应用（含本应用关联公司）单独或共同为您提供服务，且在该服务结束后，其将被禁止访问包括其以前能够访问的所有这些资料。\n\n(B) 本应用亦不允许任何第三方以任何手段收集、编辑、出售或者无偿传播您的个人信息。任何本应用平台用户如从事上述活动，一经发现，本应用有权立即终止与该用户的服务协议。\n\n(C) 为服务用户的目的，本应用可能通过使用您的个人信息，向您提供您感兴趣的信息，包括但不限于向您发出产品和服务信息，或者与本应用合作伙伴共享信息以便他们向您发送有关其产品和服务的信息（后者需要您的事先同意）。\n\n1. 信息披露\n\n在如下情况下，本应用将依据您的个人意愿或法律的规定全部或部分的披露您的个人信息：\n\n(A) 根据法律的有关规定，或者行政或司法机构的要求，向第三方或者行政、司法机构披露；\n\n(B) 如您出现违反中国有关法律、法规或者本应用服务协议或相关规则的情况，需要向第三方披露；\n\n(C) 其它本应用根据法律、法规或者网站政策认为合适的披露。\n\n2. 信息安全\n\n本应用帐号均有安全保护功能，确保您的信息不丢失，不被滥用和变造。\n\n3.本隐私政策的更改\n\n(A)如果决定更改隐私政策，我们会在本政策中、本公司网站中以及我们认为适当的位置发布这些更改，以便您了解我们如何收集、使用您的个人信息，哪些人可以访问这些信息，以及在什么情况下我们会透露这些信息。\n\n(B)本公司保留随时修改本政策的权利，因此请经常查看。如对本政策作出重大更改，本公司会通过网站通知的形式告知。\n\n4.本APP获取您的权限\n\n包括通知权限、保存图片到相册权限。\n\n5.可能间接的收集到您的信息\n\n我们的产品集成友盟+SDK，友盟+SDK需要收集您的设备Mac地址、唯一设备识别码（IMEI/android ID/IDFA/OPENUDID/GUID/IP地址/SIM 卡 IMSI 信息）以提供统计分析服务，并通过地理位置校准报表数据准确性，提供基础反作弊能力。',
          'contact me': '请联系我',
          'quit': '退出',
          'agree': '同意',
          'exercises': "运动",
          'exercise_steps': "动作要点",
          'exercise_breath': "呼吸",
          'exercise_goal': "动作目的",
          'exercise_cobras': "眼镜蛇式",
          'exercise_cobras_effect': "缓解压力和疲劳",
          'exercise_cobras_action_1': '将双手手掌向下放在肩膀下方的地面上',
          'exercise_cobras_action_2': '伸直手臂，将胸部抬离地面',
          'exercise_cobras_action_3': '向上凝视并保持腹部收紧',
          'exercise_cobras_breath_1': '自然呼吸',
          'exercise_cobras_target': '缓解压力和疲劳，伸展胸部、肩部和腹部的肌肉，加强肩膀和手臂',
          'exercise_frog_press': "蛙式蹬腿",
          'exercise_frog_effect': "增强臀部力量",
          'exercise_frog_press_action_1':
              '仰卧，膝盖弯曲成90度，像青蛙一样外翻。确保脚后跟贴合在一起，并像身体的方向弯曲双脚',
          'exercise_frog_press_action_2': '腹部收紧，同时保持你的手臂平铺在地面上',
          'exercise_frog_press_action_3': '以45度角将双腿伸直并远离身体，再回到起始位置，重复多次',
          'exercise_frog_press_breath_1': '收腿时，吸气',
          'exercise_frog_press_breath_2': '伸腿时，呼气',
          'exercise_frog_press_target':
              '蛙式蹬腿是一种基本的核心和臀部强化运动，还可以提高整个下背部、臀部和脊柱的稳定性',
          'exercise_inchworm': "蟥式",
          'exercise_inchworm_effect': "提升胸部、手臂和核心力量",
          'exercise_inchworm_action_1': "保持身体直立，站在瑜伽垫的后边缘",
          'exercise_inchworm_action_2': "身体向前弯曲，双手沿着地板向前伸出，双脚保持原位",
          'exercise_inchworm_action_3':
              "继续将你的手臂伸展过平板支撑的位置。你的手臂应该高于你的头，你的脚仍然应该在垫子的后面",
          'exercise_inchworm_action_4': "收回手臂，直立身体，回到初始状态",
          'exercise_inchworm_breath_1': "自然呼吸",
          'exercise_inchworm_target': "蟥式增强您的手臂、胸部、上背部、下背部和腹肌",
          'exercise_jumping-jack': "开合跳",
          'exercise_jumping-jack_effect': "很棒的全身运动",
          'exercise_jumping-jack_action_1': "双脚并拢站直，双手放在身体两侧",
          'exercise_jumping-jack_action_2': "跳起来，双脚分开，双手并拢举过头顶",
          'exercise_jumping-jack_action_3': "再次跳跃并返回起始位置",
          'exercise_jumping-jack_action_4': "重复多次",
          'exercise_jumping-jack_breath_1': "自然呼吸",
          'exercise_jumping-jack_target':
              "开合跳是一种很好的全身运动，可以增强有氧健身，强身健体，促进放松。这项运动还可以提高肌肉耐力，增加身体的新陈代谢率，并有助于减肥",
          'exercise_jumping-squats': "跳跃深蹲",
          'exercise_jumping-squats_effect': "下半身的全面锻炼",
          'exercise_jumping-squats_action_1': "双脚与肩同宽站立，膝盖微微弯曲",
          'exercise_jumping-squats_action_2': "弯曲你的膝盖并下降到一个全蹲位置",
          'exercise_jumping-squats_action_3':
              "推动身体向上跳跃并离开地板，延伸到腿部。 双腿完全伸展后，双脚离地面几英寸（或更多）",
          'exercise_jumping-squats_action_4':
              "通过你的脚（脚趾、球、足弓、脚后跟）下降并控制你的着陆，然后再次下降到深蹲进行另一次爆发性跳跃",
          'exercise_jumping-squats_action_5': "落地后立即重复下一次跳跃",
          'exercise_jumping-squats_breath_1': "自然呼吸",
          'exercise_jumping-squats_target': "跳跃深蹲锻炼你的下半身肌肉以及你的核心：腹肌、臀肌、腘绳肌和下背部",
          'exercise_lunge': "弓步运动",
          'exercise_lunge_effect': "增强你的下半身",
          'exercise_lunge_action_1': "直立你的身体",
          'exercise_lunge_action_2':
              "一只脚向前迈一步，直到你的腿成 90 度角。 你的后膝盖应该保持与地面平行，你的前膝盖不应该超过你的脚趾",
          'exercise_lunge_action_3': "抬起你的前弓腿，身体回到起始位置",
          'exercise_lunge_breath_1': "自然呼吸",
          'exercise_lunge_target': "弓步是一种阻力运动，可用于帮助加强您的下半身，包括：股四头肌、腘绳肌、臀大肌、小腿",
          'exercise_punches': "拳击",
          'exercise_punches_effect': "锻炼您的速度、敏捷性和力量",
          'exercise_punches_action_1': "站立，双脚分开略宽于肩部距离，膝盖略微弯曲。 收紧核心以保持中心静止",
          'exercise_punches_action_2': "以稳定的速度一次打出一只手臂",
          'exercise_punches_action_3': "重复上述动作",
          'exercise_punches_breath_1': "自然呼吸",
          'exercise_punches_target':
              "拳击是一种拳击动作，经常用于提高速度、敏捷性和力量。 这项运动针对您的肩膀、肱三头肌和背阔肌，有助于锻炼和塑造您的上半身",
          'exercise_reverse-crunches': "反向仰卧起坐",
          'exercise_reverse-crunches_effect': "增强腹直肌",
          'exercise_reverse-crunches_action_1':
              "以传统的紧缩姿势躺在地上，双脚平放在地板上，双手放在头下，肘部宽",
          'exercise_reverse-crunches_action_2':
              "将下背部压入地板并拉入肚脐以将脚抬离地板。 以 90 度角弯曲膝盖，将它们保持在一起",
          'exercise_reverse-crunches_action_3':
              "使用核心，将膝盖拉向胸部，使尾骨抬离地面。 同时进行传统的仰卧起坐，将肩胛骨抬离地面，使用腹肌而不是手来抬起头部和肩膀",
          'exercise_reverse-crunches_action_4':
              "慢慢降低肩膀、臀部和腿部，回到起始位置。 当脚刚好在地板上方时停止",
          'exercise_reverse-crunches_action_5': "重复上述动作",
          'exercise_reverse-crunches_breath_1': "自然呼吸",
          'exercise_reverse-crunches_target': "这个动作可以增强你的腹直肌，减轻你脖子的压力",
          'exercise_seated-abs-circles': "坐式腹肌转圈",
          'exercise_seated-abs-circles_effect': "增强腹部力量",
          'exercise_seated-abs-circles_action_1': "坐下，双腿抬起，手掌放在身后的地面上",
          'exercise_seated-abs-circles_action_2': "弯曲你的手臂并将你的上半身向后倾斜",
          'exercise_seated-abs-circles_action_3': "将双腿顺时针转圈",
          'exercise_seated-abs-circles_action_4': "重复上述动作",
          'exercise_seated-abs-circles_breath_1': "自然呼吸",
          'exercise_seated-abs-circles_target': "这个动作将增强你的腹部力量",
          'exercise_shoulder-stretch': "肩部伸展",
          'exercise_shoulder-stretch_effect': "放松肩部",
          'exercise_shoulder-stretch_action_1': "放松你的肩部",
          'exercise_shoulder-stretch_action_2': "将一只手臂举到肩膀的高度，然后将其伸到胸前",
          'exercise_shoulder-stretch_action_3':
              "用另一只手臂朝你的方向轻轻拉动手臂。这将帮助你得到一个温和的伸展。保持大约6秒钟",
          'exercise_shoulder-stretch_action_4': "重复2-4次",
          'exercise_shoulder-stretch_breath_1': "自然呼吸",
          'exercise_shoulder-stretch_target': "放松肩部",
          'exercise_squat-kick': "深蹲踢",
          'exercise_squat-kick_effect': "增强你的下半身",
          'exercise_squat-kick_action_1': "从双脚开始，与肩同宽",
          'exercise_squat-kick_action_2': "弯曲膝盖并将臀部放下，直到双腿成 90 度角",
          'exercise_squat-kick_action_3': "站起来，用你的右腿向前踢（每次重复交替踢腿）",
          'exercise_squat-kick_action_4': "完成了一次重复",
          'exercise_squat-kick_breath_1': "自然呼吸",
          'exercise_squat-kick_target':
              "深蹲踢是一种健美操和增强式运动，主要针对臀部肌肉，在较小程度上也针对小腿、腘绳肌、髋屈肌、大腿外侧和股四头肌",
          'exercise_staggered-push-ups': "交错俯卧撑",
          'exercise_staggered-push-ups_effect': "增强上半身力量",
          'exercise_staggered-push-ups_action_1':
              "双腿向后伸展，双手交错放置，一只手高于另一只手，分开略宽于肩宽",
          'exercise_staggered-push-ups_action_2': "开始弯曲你的肘部并降低你的胸部，直到它刚好在地板上方",
          'exercise_staggered-push-ups_action_3': "伸展双臂向上推，然后反转手的位置",
          'exercise_staggered-push-ups_action_4': "重复上述动作",
          'exercise_staggered-push-ups_breath_1': "自然呼吸",
          'exercise_staggered-push-ups_target':
              "交错的手臂俯卧撑可以锻炼你的胸部、肩膀、三头肌、二头肌和手臂。 这个动作可以增强上半身的力量，有助于调节和收紧你的核心",
          'exercise_step-up-on-chair': "上椅子",
          'exercise_step-up-on-chair_effect': "增强你的平衡性",
          'exercise_step-up-on-chair_action_1': "双手叉腰",
          'exercise_step-up-on-chair_action_2': "右脚首先踏上椅子",
          'exercise_step-up-on-chair_action_3': "然后左脚踏上椅子",
          'exercise_step-up-on-chair_action_4': "右脚离开椅子，踏到地面上",
          'exercise_step-up-on-chair_action_5': "左脚离开椅子，踏到地面上",
          'exercise_step-up-on-chair_breath_1': "自然呼吸",
          'exercise_step-up-on-chair_target':
              "上椅子练习的目的和意图是帮助改善您的平衡。 它还有助于锻炼身体的各种肌肉。 锻炼的主要肌肉是下半身的肌肉。 这些包括腘绳肌、股四头肌和臀肌",
          'exercise_t-plank': "T型平板支撑",
          'exercise_t-plank_effect': "增强上半身力量",
          'exercise_t-plank_action_1': "双手直接放在肩膀下方，进入传统的俯卧撑姿势",
          'exercise_t-plank_action_2':
              "收缩腹肌，同时旋转身体，转动双脚，将一只手臂伸直向天空，另一只手牢牢踩在地面上，使身体形成字母 T",
          'exercise_t-plank_action_3': "回到起始俯卧撑位置，然后重复",
          'exercise_t-plank_action_4': "完成一侧的次数后，换边重复",
          'exercise_t-plank_breath_1': "自然呼吸",
          'exercise_t-plank_target': "T型平板支撑可以增强您的脊椎、菱形肌和斜方肌，以及您的腹部肌肉",
          'exercise_wide-arm-push-up': "宽臂俯卧撑",
          'exercise_wide-arm-push-up_effect': "增强上半身力量",
          'exercise_wide-arm-push-up_action_1': "从双手比肩膀宽的平板位置开始",
          'exercise_wide-arm-push-up_action_2': "从双手比肩膀宽的平板位置开始",
          'exercise_wide-arm-push-up_action_3': "当您将身体向地板放低时，慢慢地将肘部向外弯曲",
          'exercise_wide-arm-push-up_action_4': "当你的胸部刚好低于肘部时暂停",
          'exercise_wide-arm-push-up_action_5':
              "当你用双手按压将你的身体抬回到起始位置时，让你的核心力量参与进来",
          'exercise_wide-arm-push-up_action_6': "做 1 到 3 组，每组 8 到 15 次重复",
          'exercise_wide-arm-push-up_breath_1': "自然呼吸",
          'exercise_wide-arm-push-up_target':
              "宽俯卧撑提供了一项具有挑战性的上身锻炼，主要针对胸部、肩膀和上臂的肌肉。 这种俯卧撑变式还可以帮助增强您的核心力量，也可以帮助保护您的背部",
          'quit_milktea': '戒奶茶',
          'quit_smoking': '戒烟',
          'quit_soap_opera': '戒肥皂剧',
          'quit_friedchicken': '戒炸鸡',
          'quit_cola': '戒可乐',
          'quit_drinking': '戒酒',
          'quit_chips': '戒薯条',
          'quit_hamburger': '戒汉堡包',
          'quit_snacks': '戒零食',
          'quit_icecream': '戒冰激凌',
          'quit_spicy': '戒辣',
          'quit_crayfish': '戒小龙虾',
          'quit_friedseries': '戒炸串',
          'quit_barbecue': '戒烧烤',
          'quit_masturbation': '戒自慰',
          'quit_sugar': '戒糖',
          'quit_carbohydrate': '戒碳水',
          'quit_coffee': '戒咖啡',
          'quit_sex': '戒色',
          'start_healthy_lifestyle': '开启健康的生活方式',
          'record': '记录',
          'journey_lower': '历程',
          'give_up_promote': '真的要放弃吗？'
        },
        'en_US': {
          'quit_bad_habit': 'Quit Bad Habits',
          'health_life': 'Start a healthy life',
          'challenge_target': 'Challenge Goals',
          'start_at': "start at:",
          'days': "days",
          'all': "all",
          'progressing': 'ongoing',
          'completed': 'completed',
          'hours': 'hours',
          'mins': 'mins',
          'secs': 'secs',
          'congraulations': 'Congraulations, achieved your goal!',
          'regret': 'You have given up your goal',
          'journey': 'Journey',
          'challenge_begin': 'challenge begin',
          'challenge_completed': 'challenge completed',
          'challenge_giveup': 'challenge gived up',
          'giveup_challenge': 'give up challenge',
          'cancel': 'cancel',
          'save': 'save',
          'select_day': 'days of persistence:',
          'custom_days': 'custom days:',
          'save success': 'save successfully',
          'save failed': 'save failed',
          'select_color': 'select color:',
          'notify_sound': 'notify sound:',
          'notify_time': 'notify time:',
          'select_sound': 'Select Notify Sound',
          'confirm': 'confirm',
          'try_exercise': 'try to do exercises!',
          'giveup': 'gived up',
          'target is ongoing': 'this target is ongoing...',
          'set days': 'please set target days',
          'go to setting': 'Go to Setting',
          'album permission':
              'save image needs system album permission, go to setting',
          'go to': 'go',
          'notification setting': 'Notification Setting',
          'notification permission':
              'receive notifications needs system notification permission, go to setting',
          'sound_lg': 'LG classic',
          'sound_pikachu': 'Pikachu',
          'sound_ringtones': 'Ringtones',
          'sound_samsung': 'Samsung classic',
          'sound_spring': 'Raise',
          'refresh_idle_text': 'Pull down Refresh',
          'refresh_releasing_text': 'Release to refresh',
          'refresh_complete_text': 'Refresh Completed',
          'push_text_1': 'Congratulations, Great Start!',
          'push_text_2': 'You have insisted on ',
          'push_text_3': ' days, Keep going!',
          'push_text_4': 'Congratulations, You have achieved your goal!',
          'help': 'Help',
          'praise': 'Praise',
          'feedback': 'Cooperate and Feedback',
          'policy': 'Privacy Policy',
          'contact me': 'Please contact me',
          'quit': 'quit',
          'agree': 'agree',
          'policy_text':
              'This application respects and protects the personal privacy of all service users. In order to provide you with more accurate and personalized services. This application will treat this information with a high degree of diligence and prudence. Except as otherwise provided in this privacy policy, this application will not disclose or provide this information to third parties without your prior permission. This application will update this privacy policy from time to time. When you agree to this application service use agreement, you are deemed to have agreed to the entire content of this privacy policy. This privacy policy is an integral part of this application service usage agreement.\n\n(A) This app will not provide, sell, rent, share or trade your personal information to any unrelated third party, unless you get your permission in advance, or the third party and this app (including this app affiliate) individually or jointly To provide you with services, and after the end of the service, it will be prohibited from accessing all these materials that it was able to access before.\n\n(B) This application also does not allow any third party to collect, edit, sell or disseminate your personal information by any means. If any user of this application platform engages in the above activities, once discovered, this application has the right to immediately terminate the service agreement with the user.\n\n(C) For the purpose of serving users, this application may use your personal information to provide you with information that you are interested in, including but not limited to sending you product and service information, or sharing information with partners of this application for them Send you information about its products and services (the latter requires your prior consent).\n\n1. Information Disclosure\n\nUnder the following circumstances, this application will disclose your personal information in whole or in part according to your personal wishes or legal requirements:\n\n(A) Disclosure to a third party or administrative or judicial organization in accordance with the relevant provisions of the law or the requirements of an administrative or judicial organization;\n\n(B) If you violate relevant Chinese laws, regulations, or this application service agreement or related rules, you need to disclose to a third party;\n\n(C) Other disclosures deemed appropriate by this application in accordance with laws, regulations or website policies.\n\n2. Information Security\n\nThis application account has security protection functions to ensure that your information is not lost, abused and altered.\n\n3. Changes to this privacy policy\n\n(A) If you decide to change the privacy policy, we will post these changes in this policy, on the company’s website, and where we deem appropriate, so that you can understand how we collect and use your personal information and who can access this information. And under what circumstances we will disclose this information.\n\n(B) The company reserves the right to modify this policy at any time, so please check it frequently. If you make a major change to this policy, the company will notify you through a website notice.\n\n4. This APP gets your permission\n\nIncluding notification permissions, save pictures to album permissions.\n\n5.Your information may be collected indirectly\n\nOur product integrates Umeng+SDK, Umeng+SDK needs to collect your device Mac address, unique device identification code (IMEI/android ID/IDFA/OPENUDID/GUID/IP address/SIM card IMSI information) to provide statistical analysis services , And calibrate the accuracy of the report data by geographic location to provide basic anti-cheating capabilities.',
          'exercises': "Exercises",
          'exercise_steps': "Steps",
          'exercise_breath': "Breath",
          'exercise_goal': "Goal",
          'exercise_cobras': "Cobras",
          'exercise_cobras_effect': "Relieves stress and fatigue",
          'exercise_cobras_action_1':
              'Place your hands palms down on the ground beneath your shoulders',
          'exercise_cobras_action_2':
              'Lift your chest up off the ground by straightening your arms',
          'exercise_cobras_action_3':
              'Gaze upwards and keep your abdominals engaged',
          'exercise_cobras_breath_1': 'Natural breathing',
          'exercise_cobras_target':
              'Relieves stress and fatigue. Stretches the muscles in the chest, shoulders, and abdominals, Strengthens the shoulders and the arms',
          'exercise_frog_press': "Frog Press",
          'exercise_frog_effect': "Enhance hip strength",
          'exercise_frog_press_action_1':
              'Lie on your back with your knees bent to 90 degrees, turning them outwards like a frog. Make sure to keep your heels pressed together while flexing your feet towards you',
          'exercise_frog_press_action_2':
              'Tighten your stomach and crunch up, Place your arms down by your side, hovering just above the floor',
          'exercise_frog_press_action_3':
              'Straighten your legs away from your body at a 45-degree angle. Return to the starting position, completing the desired amount of repetitions',
          'exercise_frog_press_breath_1': 'Inhale when withdraw your legs',
          'exercise_frog_press_breath_2': 'Exhale when straighten your legs',
          'exercise_frog_press_target':
              'The frog press is a basic core- and glutes-strengthening exercise that also improves stability throughout the lower back, hips, and spine',
          'exercise_inchworm': "inchworm",
          'exercise_inchworm_effect': "Improve chest,arm,core strength",
          'exercise_inchworm_action_1':
              "Keep your body upright and stand on the back edge of the yoga mat",
          'exercise_inchworm_action_2':
              "Hinge your body forward and walk your hands out in front of you along the floor, keeping your feet in place",
          'exercise_inchworm_action_3':
              "Continue walking your arms out past the plank position. Your arms should be above your head and your feet should still be at the back of the mat",
          'exercise_inchworm_action_4':
              "Withdraw the arms, stand upright, and return to the initial state",
          'exercise_inchworm_breath_1': "Natural breathing",
          'exercise_inchworm_target':
              "The inchworm strengthens your arms, chest, upper back, lower back and abs",
          'exercise_jumping-jack': "Jumping Jack",
          'exercise_jumping-jack_effect': "Great full body exercise",
          'exercise_jumping-jack_action_1':
              "Stand straight with your feet together and hands by your sides",
          'exercise_jumping-jack_action_2':
              "Jump up, spread your feet and bring both hands together above your head",
          'exercise_jumping-jack_action_3':
              "Jump again and return to the starting position",
          'exercise_jumping-jack_action_4': "Repeat until the set is complete",
          'exercise_jumping-jack_breath_1': "Natural breathing",
          'exercise_jumping-jack_target':
              "Jumping jacks are a great full body exercise that enhances aerobic fitness, strengthens the body, and promotes relaxation. This exercise also improves muscle endurance, increases the body’s metabolic rate, and helps with weight loss",
          'exercise_jumping-squats': "Jumping Squats",
          'exercise_jumping-squats_effect': "Full exercise for the lower body",
          'exercise_jumping-squats_action_1':
              "Stand with feet shoulder width and knees slightly bent",
          'exercise_jumping-squats_action_2':
              "Bend your knees and descend to a full squat position",
          'exercise_jumping-squats_action_3':
              "Engage through the quads, glutes, and hamstrings and propel the body up and off the floor, extending through the legs. With the legs fully extended, the feet will be a few inches (or more) off the floor",
          'exercise_jumping-squats_action_4':
              "Descend and control your landing by going through your foot (toes, ball, arches, heel) and descend into the squat again for another explosive jump",
          'exercise_jumping-squats_action_5':
              "Upon landing immediately repeat the next jump",
          'exercise_jumping-squats_breath_1': "Natural breathing",
          'exercise_jumping-squats_target':
              "This exercise uses your lower body muscles as well as your core: abdominals, glutes, hamstrings, and lower back",
          'exercise_lunge': "Lunge",
          'exercise_lunge_effect': "Full exercise for the lower body",
          'exercise_lunge_action_1': "Start by standing up tall",
          'exercise_lunge_action_2':
              "Step forward with one foot until your leg reaches a 90-degree angle. Your rear knee should remain parallel to the ground and your front knee shouldn’t go beyond your toes",
          'exercise_lunge_action_3':
              "Lift your front lunging leg to return to the starting position",
          'exercise_lunge_breath_1': "Natural breathing",
          'exercise_lunge_target':
              "The lunge is a resistance exercise that can be used to help strengthen your lower body, including your quadriceps, hamstrings, glutes, calves",
          'exercise_punches': "Punches",
          'exercise_punches_effect': "Benift for your speed, agility, strength",
          'exercise_punches_action_1':
              "Stand with feet slightly wider than shoulder distance apart and bend knees slightly. Tighten the core to keep your center still",
          'exercise_punches_action_2':
              "Punch out one arm at a time at a steady pace",
          'exercise_punches_action_3': "Repeat above actions",
          'exercise_punches_breath_1': "Natural breathing",
          'exercise_punches_target':
              "Punch is a boxing move that is frequently used for speed, agility, and strength. This exercise targets your shoulders, triceps, and lats and helps to tone and sculpt your upper body",
          'exercise_reverse-crunches': "Reverse Crunches",
          'exercise_reverse-crunches_effect':
              "Strengthens your rectus abdominis",
          'exercise_reverse-crunches_action_1':
              "Lie on the ground in a traditional crunch position, feet flat on the floor and hands underneath the head, elbows wide",
          'exercise_reverse-crunches_action_2':
              "Press lower back into the floor and pull in the belly button to lift feet off the floor. Bend knees at a 90-degree angle, keeping them together",
          'exercise_reverse-crunches_action_3':
              "Using core, draw knees toward chest so that tailbone raises off the ground. Simultaneously perform a traditional crunch, lifting shoulder blades off the floor and using abs, not hands, to lift head and shoulders",
          'exercise_reverse-crunches_action_4':
              "Slowly lower shoulders, hips, and legs to return to the starting position. Stop when feet are just above the floor",
          'exercise_reverse-crunches_action_5': "Repeat above actions",
          'exercise_reverse-crunches_breath_1': "Natural breathing",
          'exercise_reverse-crunches_target':
              "This action strengthens your rectus abdominis, takes strain off your neck",
          'exercise_seated-abs-circles': "Seated Abs circles",
          'exercise_seated-abs-circles_effect': "Enhance abdominal strength",
          'exercise_seated-abs-circles_action_1':
              "Sit with your legs lifted and your palms behind you on the ground",
          'exercise_seated-abs-circles_action_2':
              "Bend your arms and lean your upper body back",
          'exercise_seated-abs-circles_action_3':
              "Move your legs clockwise in circles",
          'exercise_seated-abs-circles_action_4': "Repeat above actions",
          'exercise_seated-abs-circles_breath_1': "Natural breathing",
          'exercise_seated-abs-circles_target': "Enhance abdominal strength",
          'exercise_shoulder-stretch': "Shoulder Stretch",
          'exercise_shoulder-stretch_effect': "Relax your shoulders",
          'exercise_shoulder-stretch_action_1': "Relax your shoulders",
          'exercise_shoulder-stretch_action_2':
              "Raise one arm to shoulder height, and reach it across your chest",
          'exercise_shoulder-stretch_action_3':
              "Pull the arm slightly toward you with your other arm. This will help you get a gentle stretch. Hold for about 6 seconds",
          'exercise_shoulder-stretch_action_4': "Repeat 2 to 4 times",
          'exercise_shoulder-stretch_breath_1': "Natural breathing",
          'exercise_shoulder-stretch_target': "Relax your shoulders",
          'exercise_squat-kick': "Squat Kick",
          'exercise_squat-kick_effect': "Full exercise for the lower body",
          'exercise_squat-kick_action_1':
              "Start with your feet about shoulder width apart",
          'exercise_squat-kick_action_2':
              "Bend at the knees and drop your butt down till your legs make a 90 degree angle",
          'exercise_squat-kick_action_3':
              "Stand back up and kick forward with you right leg (alternate kicking legs each repetition)",
          'exercise_squat-kick_action_4': "This completes one repetition",
          'exercise_squat-kick_breath_1': "Natural breathing",
          'exercise_squat-kick_target':
              "Squat kick is a calisthenics and plyometrics exercise that primarily targets the glutes and to a lesser degree also targets the calves, hamstrings, hip flexors, outer thighs and quads",
          'exercise_staggered-push-ups': "Staggered Push Ups",
          'exercise_staggered-push-ups_effect': "Enhance upper body strength",
          'exercise_staggered-push-ups_action_1':
              "With your legs extended back, place the hands staggered, with one being higher than the other and slightly wider than shoulder-width apart",
          'exercise_staggered-push-ups_action_2':
              "Start bending your elbows and lower your chest until it’s just above the floor",
          'exercise_staggered-push-ups_action_3':
              "Extend your arms to push back up and then reverse your hand position",
          'exercise_staggered-push-ups_action_4': "Repeat above actions",
          'exercise_staggered-push-ups_breath_1': "Natural breathing",
          'exercise_staggered-push-ups_target':
              "The staggered arm push up works your chest, shoulders, triceps, biceps, and arms. This move strengthens the upper body and helps to tone and tighten your core",
          'exercise_step-up-on-chair': "Step Up On Chair",
          'exercise_step-up-on-chair_effect': "Improving your balance",
          'exercise_step-up-on-chair_action_1': "Hands on hips",
          'exercise_step-up-on-chair_action_2': "Step Right foot on the chair",
          'exercise_step-up-on-chair_action_3':
              "Then Step Left foot on the chair",
          'exercise_step-up-on-chair_action_4':
              "Right foot leave the chair and step on the ground",
          'exercise_step-up-on-chair_action_5':
              "Left foot leave the chair and step on the ground",
          'exercise_step-up-on-chair_breath_1': "Natural breathing",
          'exercise_step-up-on-chair_target':
              "The purpose and intent of the step up onto chair exercise is to aid in improving your balance. It also aids in exercising various muscles of the body. The main muscles exercised are those that are in the lower body. These include the hamstring, the quadriceps, and the glutes",
          'exercise_t-plank': "T Plank",
          'exercise_t-plank_effect': "Enhance upper body strength",
          'exercise_t-plank_action_1':
              "Get into a traditional pushup position with your hands directly below your shoulders",
          'exercise_t-plank_action_2':
              "Contract your abs while rotating your body, pivoting your feet, and extending one of your arms straight up to the sky, with your other hand firmly planted into the ground so your body creates the letter T",
          'exercise_t-plank_action_3':
              "Return to the starting pushup position, then repeat",
          'exercise_t-plank_action_4':
              "Once you’ve completed the reps on one side, switch sides and repeat",
          'exercise_t-plank_breath_1': "Natural breathing",
          'exercise_t-plank_target':
              "The plank strengthens your spine, your rhomboids and trapezius, and your abdominal muscles",
          'exercise_wide-arm-push-up': "Wide Arm Push Up",
          'exercise_wide-arm-push-up_effect': "Enhance upper body strength",
          'exercise_wide-arm-push-up_action_1':
              "Start in plank position with your hands wider than your shoulders",
          'exercise_wide-arm-push-up_action_2':
              "Face your fingers forward or slightly to the outside",
          'exercise_wide-arm-push-up_action_3':
              "Slowly bend your elbows out to the side as you lower your body toward the floor",
          'exercise_wide-arm-push-up_action_4':
              "Pause when your chest is just below your elbows",
          'exercise_wide-arm-push-up_action_5':
              "Engage your core as you press into your hands to lift your body back to the starting position",
          'exercise_wide-arm-push-up_action_6':
              "Do 1 to 3 sets of 8 to 15 repetitions",
          'exercise_wide-arm-push-up_breath_1': "Natural breathing",
          'exercise_wide-arm-push-up_target':
              "Wide pushups offer a challenging upper-body workout that targets the muscles in your chest, shoulders, and upper arms. This pushup variation can also help build your core strength, and it may help protect your back, too",
          'quit_milktea': 'Quit Milk Tea',
          'quit_smoking': 'Quit Smoking',
          'quit_soap_opera': 'Quit Soap Opera',
          'quit_friedchicken': 'Quit Fried Chicken',
          'quit_cola': 'Quit Cola',
          'quit_drinking': 'Quit Drinking',
          'quit_chips': 'Quit Chips',
          'quit_hamburger': 'Quit Hamburger',
          'quit_snacks': 'Quit Snacks',
          'quit_icecream': 'Quit Icecream',
          'quit_spicy': 'Quit Spicy Food',
          'quit_crayfish': 'Quit Crayfish',
          'quit_friedseries': 'Quit Fried Series',
          'quit_barbecue': 'Quit Barbecue',
          'quit_masturbation': 'Quit Masturbation',
          'quit_sugar': 'Quit Sugar',
          'quit_carbohydrate': 'Quit Carbohydrate',
          'quit_coffee': 'Quit Coffee',
          'quit_sex': 'Quit Sex',
          'start_healthy_lifestyle': 'Start a healthy lifestyle',
          'record': 'record',
          'journey_lower': 'journey',
          'give_up_promote': 'Really want to give up?'
        }
      };
}
